
name: global-enviroment
env:
  VERSION: $(Get-Content version)

on:
  workflow_dispatch:

jobs:
  print:
    runs-on: [ windows-latest ]
    steps:
    - name: print env
      run: |
        ${{ env.VERSION }}